version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trab_3_esii
    ports:
      -"3001:3000"
    volumes:
    - .:/app
    - /app/node_modules
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=apiCursos

    depends_on:
      - mysql

    command: npm run start:dev
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: apiCursos

    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  volumes:
    mysql-data:
    


      
